services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_management
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
  php-apache:
    platform: linux/x86_64
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/attendance_management
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
