version: 2.1
 
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys
            - run: ssh -i ${KEY_PATH} ${USER_NAME}@${HOST_NAME} 'cd /var/www/attendance_management && sudo git pull && cd src && npm run build'
 
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: main
