---
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - vue
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/recommended